# XLFusion V1.0 Configuration
# =====================================
# Centralized configuration for XLFusion checkpoint merger
# This file controls all aspects of model merging behavior, naming, and output


# =====================================
# MODEL OUTPUT CONFIGURATION
# =====================================
# Controls how merged models are named and saved
model_output:
  # Base name for all merged models (e.g., "XLFusion" produces "XLFusion_V1.safetensors")
  base_name: "XLFusion"

  # Version prefix format - determines how versions are numbered
  # "V" creates V1, V2, V3... | "v" creates v1, v2, v3... | "Ver" creates Ver1, Ver2...
  version_prefix: "V"

  # File extension for output models - must be .safetensors for SDXL compatibility
  file_extension: ".safetensors"

  # Directory where merged models will be saved
  output_dir: "output"

  # Directory where merge metadata and audit logs are stored
  metadata_dir: "metadata"

  # Automatically increment version numbers to prevent overwriting existing models
  # true = auto-detect next version | false = requires manual version specification
  auto_version: true


# =====================================
# DIRECTORY STRUCTURE
# =====================================
# Defines the folder structure used by XLFusion
directories:
  # Input checkpoint files (.safetensors) - place your base SDXL models here
  models: "models"

  # LoRA files (.safetensors) - only used in Legacy mode for LoRA baking
  loras: "loras"

  # Output directory for merged models - final results saved here
  output: "output"

  # Metadata and audit logs - detailed merge information for reproducibility
  metadata: "metadata"


# =====================================
# DEFAULT MERGE SETTINGS
# =====================================
# Pre-configured default values for merge operations
merge_defaults:
  # Legacy mode: Traditional weighted merging with block-level control
  legacy:
    # Cross-attention boost factor (1.0 = no boost, >1.0 = enhanced prompt adherence)
    cross_attention_boost: 1.0

    # Down blocks multiplier (affects composition and structure at 64x, 32x, 16x, 8x resolutions)
    down_blocks_multiplier: 1.0

    # Mid blocks multiplier (affects abstract processing in 8x latent space)
    mid_blocks_multiplier: 1.0

    # Up blocks multiplier (affects reconstruction and final output at 8x, 16x, 32x, 64x)
    up_blocks_multiplier: 1.0

  # PerRes mode: Per-resolution block assignment for precise control
  perres:
    # Cross-attention locks for improved prompt consistency across models
    # false = independent attention | true = locked attention patterns
    cross_attention_locks: false


# =====================================
# APPLICATION SETTINGS
# =====================================
# Core application configuration and behavior
app:
  # Tool identifier used in metadata and audit logs
  # This name appears in all generated metadata files for tracking purposes
  tool_name: "XLFusion"

  # Application version - recorded in metadata for merge reproducibility
  # Format: "major.minor" (e.g., "1.0", "1.1", "2.0")
  version: "1.0"